### PR TITLE
Bindings constructor parse from YAML

### PR DESCRIPTION
**Pull request by jerinphilip**
Parse from YAML version, expensive right now due to allocations

### CODE REVIEW

**Comment by kpu** [comment]
Oh no, the YAML form of request options keeps coming back.  Why??????

**Comment by jerinphilip** [comment]
> Oh no, the YAML form of request options keeps coming back. Why??????

So, #139 is a no-YAML solution, you can let it in as-is. This PR (#141) is behind it. There's also an alternate of #140 behind #139. I gain some WASM exp++ even if this doesn't go in. Fair enough?

**Review by kpu — CHANGES_REQUESTED** [review]
Blocking what is apparently yaml practice, then muting.

**Comment by jerinphilip** [comment]
Abandoned.

**Pull request closed without merging**
