### PR TITLE
Fix failures when loading text shortlist

### PR DESCRIPTION
**Pull request by qianqianzhu**
This PR provides a quick patch to fix failures when loading text shortlist as mentioned in https://github.com/browsermt/bergamot-translator/issues/56#issuecomment-841855415.

`service-cli` now depends on `--check-bytearray` option to decide whether to construct `Service` from file-based loading or preloaded bytearrays. The bytearray of shortlist can only be loaded from binary shortlist. 
`--check-bytearray` option is set to true by default (assuming construct `Service` from bytearrays), thus causes failure when users provide text shortlist without setting `--check-bytearray` to false.

The `BinaryShortlistGenerator` itself did not break loading from text shortlist files. But this class can be further improved by allowing construct bytearrays from text shortlist (it is already in the code but I didn't provide the API).

Let me know what works best to fix this issue, @kpu @jerinphilip @XapaJIaMnu

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
@qianqianzhu I think we had the same discussion on another PR and we decided to keep it on by default due to wanting users to verify it. Is it possible to somehow make it conditional based on the format of the shortlist file (eg if you have a shortlist file ending on .bin, verify, else don't.)

**Comment by jerinphilip** [comment]
> Is it possible to somehow make it conditional based on the format of the shortlist file? 

Does marian's configparser allow this? CMake does which kpu did recently for a PR, I was looking for an equivalent heree. The alternative was the hard-code where I set these off when I don't have modelBytes, which you weren't particularly in favour of. I think this PR and adopting new convention is the cleanest. We'll update behaviour in the respective conversation.

https://github.com/browsermt/bergamot-translator/issues/113. The defaults everyone wants now are off, so.

**Comment by jerinphilip** [comment]
@qianqianzhu Is there anything waiting for this to be ready for review?

**Comment by qianqianzhu** [comment]
> we decided to keep it on by default due to wanting users to verify it.

I agree that. But the question is that do we want to load from bytearrays by default? (as `--check-bytearray` will also set that to true).

**Review by jerinphilip — APPROVED** [review]

**Comment by qianqianzhu** [comment]
@jerinphilip This PR is just a quick patch. I am more for fixing this issue with a more concrete solution. If you think we can further improve it, I am happy to work on it. 

> Is it possible to somehow make it conditional based on the format of the shortlist file?

We can add this condition in `BinaryShortlistGenerator` class. Let me know if you would like to change this class.

**Comment by kpu** [comment]
I don't think the name of the file should determine if it's validated!  In general, using filenames to determine behavior is bad IMO.  

The goal here is that other people can provide models with some assurance that they won't crash / reveal memory they shouldn't / otherwise pwn your computer.  And that's really a download-then-validate thing.  I don't think changing the file name makes sense.

**Comment by qianqianzhu** [comment]
The binary shortlist has a magic signature in the header, we do not need to check the filename to determine the format. The magic tells. 

It's my fault that I did not explain clearly why I want to turn off `--check-bytearray`. 
`--check-bytearray` option has two effects:
  - `true`: loading model, shortlist and vocabs from bytearrays and validate the bytearrays
  - `false`:  loading model, shortlist and vocabs from files and not validate the files

The key problem might be that `--check-bytearray` should only be responsible to determine whether to validate the bytearrays (not loading from bytearrays or files).

**Comment by kpu** [comment]
Maybe we should kill `--check-bytearray`.  The binaries provided by the user should be used if provided.  If somebody wants to check the binary data is in bounds that should happen regardless of bytearray or file name.

**Comment by XapaJIaMnu** [comment]
So in other words there should be a code that validates the non-binary lexical shortlist?

**Comment by kpu** [comment]
What I meant is `--check-bytearray` seems to refer to the user providing `bergamot-translator` with a bytearray as opposed to a file name that then contains a binary.  Whether something is checked or not has little to do with being loaded by the library user or from a file.

**Comment by qianqianzhu** [comment]
Mark this PR as a draft as more things to be done.

**Comment by qianqianzhu** [comment]
Sorry this issus takes forever. The main thing makes me struggle is that we use `check-bytearray` to decide whether we construct Service from bytearray or file names in `service-cli`.
```cpp
  if (options->get<bool>("check-bytearray")) {
    // Load legit values into bytearrays.
    memoryBundle = marian::bergamot::getMemoryBundleFromConfig(options);
  }

  marian::bergamot::Service service(options, std::move(memoryBundle));
```
As the default value of `check-bytearray` is true, then it will always load the files into memory first and construct Service from bytearray. When non-binary files loaded into memory, the crash happens.

As bytearray loading is only a use case inclusive to Mozilla, we should construct Service from file names by default, right? So we can potentially allow more file types (like model.npz, lex.s2t, vocab.json), not limited to certain binary files.

> Maybe we should kill --check-bytearray.

If we kill `--check-bytearray`, we still need a switch/option to tell `service-cli` when to construct service from bytearray (mainly for testing purpose) and when not.

So I adopted previous @jerinphilip 's approach by introducing `--bytearray` option for testing purpose only.

@XapaJIaMnu @kpu @jerinphilip let me know if you are happy with this solution.

**Review by jerinphilip — APPROVED** [review]

**Review by jerinphilip — APPROVED** [review]

**Comment by jerinphilip** [comment]
@qianqianzhu can you update the coding style and let's get this in?

**Review by jerinphilip — APPROVED** [review]

**Pull request merged**
