### PR TITLE
Update submodule ssplit-cpp

### PR DESCRIPTION
**Pull request by ugermann**
This pull request updates the submodule ssplit-cpp:

- I've forked ugermann/ssplit-cpp into browsermt/ssplit-cpp to allow bergamot-specific tweaks if needed without compromising the original project.
- The .gitmodule records in bergamot-translator have been updated accordingly. 
- All github workflows pass.
- pcre2 is treated as an cmake ExternalProject, which is downloaded, configured, and compiled when necessary (wasm compiles) or requested explicity (-DUSE_INTERNAL_PCRE2=on). 
- Obsoletes https://github.com/ugermann/ssplit-cpp/pull/10

### CODE REVIEW

**Comment by abhi-agg** [comment]
@ugermann Thanks for forking [ssplit inside bergamot](https://github.com/browsermt/ssplit-cpp) org.

One question though. The CI is not running on this repo currently. I believe we need to add workflows [similar to these ones](https://github.com/browsermt/ssplit-cpp/tree/master/.github/workflows) for testing with `USE_INTERNAL_PCRE2=on` as neither this repo nor your personal one tests this use case.

What do you think?

**Comment by ugermann** [comment]
CI is now running and I've added workflows which use the internal PCRE2.

**Comment by abhi-agg** [comment]
@ugermann Thanks for workflows to test internal PCRE2. I can approve if you add me as a reviewer here 👍 
@jerinphilip could be a 2nd reviewer for you 👍

**Review by jerinphilip — APPROVED** [review]
Approving.

**Review by abhi-agg — APPROVED** [review]
Lgtm.

**Pull request merged**
