### PR TITLE
Updated marian submodule

### PR DESCRIPTION
**Pull request by abhi-agg**
- Includes the change that fixes the binary model loading problem for wasm
 - submodule is still pointing to `wasm` branch of `browsermt/marian-dev`
     - It will be changed to point to `main` branch once the corresponding PR gets merged

### CODE REVIEW

**Comment by jerinphilip** [comment]
There's a submodule change also in https://github.com/browsermt/bergamot-translator/issues/50, for some model loading. Is this synchronized?

**Comment by abhi-agg** [comment]
> There's a submodule change also in #50, for some model loading. Is this synchronized?

The change that you mentioned is related to using models as byte array which is independent of this PR (that enables binary model loading from files) 👍

**Review by motin — APPROVED** [review]
I have no easy trajectory for testing that this works before approving, so I am approving this assuming that @abhi-agg have tested that this indeed makes binary models load and translate properly :)

**Comment by abhi-agg** [comment]
> I have no easy trajectory for testing that this works before approving, so I am approving this assuming that @abhi-agg have tested that this indeed makes binary models load and translate properly :)

Yes @motin. I tested it. It works 👍

**Review by jerinphilip — COMMENTED** [review]
Kindly link to the places this PR here helps. I'm assuming this is to bump it somewhere for the extension etc to fix and test model loads. 

I understand the information is asking is probably available scattered in the branches (marian-dev / extension) and etc, just not obvious to find and would want it here for completeness.

**Comment by abhi-agg** [comment]
> Kindly link to the places this PR here helps. I'm assuming this is to bump it somewhere for the extension etc to fix and test model loads.
> 
> I understand the information is asking is probably available scattered in the branches (marian-dev / extension) and etc, just not obvious to find and would want it here for completeness.

We are not using the .bin model files in the extension as of now because it was not working for wasm. This PR is the first step towards achieving that 👍

**Review by jerinphilip — APPROVED** [review]
> This change however fixes loading the .bin files for wasm (@XapaJIaMnu provided this fix to us). It is necessary for us to merge it to main to be able to load .bin models which are smaller in size. Therefore, it would be best if we can merge it just now.

In that case, I'm conditionally approving the changes, @abhi-agg is expected to link PR in the extension which uses the changes in this bump (ideally pre-merge, there should be a WIP draft somewhere. I guess post-merge to main is also okay).

**Comment by abhi-agg** [comment]
> Addendum: Ignore Ubuntu build failures, I'm on fixing it.

Thanks. I will merge it to main then 👍

**Comment by abhi-agg** [comment]
This submodule update was pulled in [extension code ](https://github.com/mozilla-extensions/bergamot-browser-extension) (the submodule bergamot-translator contains this change) 👍

**Pull request merged**
